// ═══════════════════════════════════════════════════════
// NetPlus — Shashank J Verified LinkedIn & Industry Network
// Sourced from Official LinkedIn Archive Export (1,933 Connections)
// ═══════════════════════════════════════════════════════
import { Contact, Interaction } from './types';

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'contact-sandeep-guna',
    user_id: 'user-shashank',
    full_name: 'Sandeep Gunasekaran',
    company: 'Visa',
    title: 'Director | Cloud Security Engineering',
    email: 'sandeep.gunasekaran@visa.example.com',
    linkedin_url: 'https://www.linkedin.com/in/sandeepguna',
    previous_company: 'Cisco Systems',
    previous_title: 'Senior Cloud Security Architect',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Key industry connection at Visa. Mentoring on enterprise cloud perimeter defense, zero-trust token issuance, and Smart Attendance zero-fraud cryptographic verification.',
    last_contacted_at: new Date(Date.now() - 38 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 140 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
  {
    id: 'contact-pravallika-varikuti',
    user_id: 'user-shashank',
    full_name: 'Pravallika Varikuti',
    company: 'Bosch Global Software Technologies',
    title: 'Software Engineer',
    email: 'pravallika.varikuti@bosch.example.com',
    linkedin_url: 'https://www.linkedin.com/in/pravallika-varikuti-9a350a240',
    previous_company: 'Bosch Engineering',
    previous_title: 'Graduate Trainee',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Bosch alumni network. Discussed automotive backend microservices and telemetry ingestion pipelines.',
    last_contacted_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'contact-nagesh-bhavi',
    user_id: 'user-shashank',
    full_name: 'Nagesh Bhavi',
    company: 'Hewlett Packard Enterprise',
    title: 'IT Developer/Engineer',
    email: 'nagesh.bhavi@hpe.example.com',
    linkedin_url: 'https://www.linkedin.com/in/nageshbhavi',
    previous_company: 'HPE Labs',
    previous_title: 'Systems Intern',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'HPE enterprise systems engineer. Syncing on hybrid cloud deployments, multi-tenant database partitions, and DevFlow Pro telemetry.',
    last_contacted_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 150 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 32 * 86400000).toISOString(),
  },
  {
    id: 'contact-chandan-u',
    user_id: 'user-shashank',
    full_name: 'Chandan U',
    company: 'Qualcomm',
    title: 'Associate Software Engineer',
    email: 'chandan.u@qualcomm.example.com',
    linkedin_url: 'https://www.linkedin.com/in/chandan-u',
    previous_company: 'Qualcomm Wireless',
    previous_title: 'Engineering Intern',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Qualcomm systems engineer. Discussed low-latency firmware and edge computing architectures for campus IoT sensors.',
    last_contacted_at: new Date(Date.now() - 44 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 160 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 44 * 86400000).toISOString(),
  },
  {
    id: 'contact-raksha-br',
    user_id: 'user-shashank',
    full_name: 'Raksha B R',
    company: 'Infineon Technologies',
    title: 'Student Intern',
    email: 'raksha.br@infineon.example.com',
    linkedin_url: 'https://www.linkedin.com/in/raksha-b-r-447490292',
    previous_company: 'JSSSTU',
    previous_title: 'Research Assistant',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Infineon Technologies semiconductor engineering collaborator. Discussed hardware-level cryptographic key stores and secure nonces.',
    last_contacted_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'contact-abhay-sj',
    user_id: 'user-shashank',
    full_name: 'Abhay S J',
    company: 'Bosch Global Software Technologies',
    title: 'AI/GenAI Intern',
    email: 'abhay.sj@bosch.example.com',
    linkedin_url: 'https://www.linkedin.com/in/abhay-s-j-767580229',
    previous_company: 'JSSSTU AI Lab',
    previous_title: 'Student Researcher',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'GenAI researcher at Bosch. Collaborating on multi-agent evaluation frameworks, LangGraph stateful DAGs, and autonomous agent orchestration.',
    last_contacted_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 110 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    id: 'contact-vachan-kashyap',
    user_id: 'user-shashank',
    full_name: 'Vachan Kashyap K N',
    company: 'Sandisk',
    title: 'Associate Reliability Engineer',
    email: 'vachan.kashyap@sandisk.example.com',
    linkedin_url: 'https://www.linkedin.com/in/vachan-kashyap-k-n-67724625a',
    previous_company: 'Western Digital',
    previous_title: 'Firmware Intern',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Storage reliability engineer at Sandisk. Reviewing LSM-tree write-ahead log benchmarks and high-throughput durability.',
    last_contacted_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'contact-divitha-nagaraju',
    user_id: 'user-shashank',
    full_name: 'Divitha Nagaraju',
    company: 'Acceldata',
    title: 'Software Engineer Intern',
    email: 'divitha.nagaraju@acceldata.example.com',
    linkedin_url: 'https://www.linkedin.com/in/divitha-nagaraju06',
    previous_company: 'JSSSTU',
    previous_title: 'Data Science Club Lead',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Data observability engineer at Acceldata. Discussed real-time stream monitoring, cluster health telemetry, and anomaly detection.',
    last_contacted_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'contact-sai-yaswitha',
    user_id: 'user-shashank',
    full_name: 'Sai Yaswitha Raavi',
    company: 'Visa',
    title: 'Cyber Security Engineer',
    email: 'sai.yaswitha@visa.example.com',
    linkedin_url: 'https://www.linkedin.com/in/raavi-sai-yaswitha',
    previous_company: 'Visa Cyber Command',
    previous_title: 'Security Analyst Intern',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Visa Cyber Security team. Discussing zero-trust authentication tokens, HMAC nonces, and anti-proxy verification gates.',
    last_contacted_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'contact-r-aswin',
    user_id: 'user-shashank',
    full_name: 'R Aswin',
    company: 'Visa',
    title: 'Semester Intern - Cyber Security Engineering',
    email: 'r.aswin@visa.example.com',
    linkedin_url: 'https://www.linkedin.com/in/r-aswin242004',
    previous_company: 'JSSSTU Cyber Defense',
    previous_title: 'Security Lead',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Cybersecurity colleague at Visa. Peer review of SHA-256 HMAC nonces, credential issuance, and hardware attestation.',
    last_contacted_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 95 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 19 * 86400000).toISOString(),
  },
  {
    id: 'contact-mahesh-narbolikar',
    user_id: 'user-shashank',
    full_name: 'Mahesh Narbolikar',
    company: 'Synopsys Inc',
    title: 'Senior Application Engineer',
    email: 'mahesh.narbolikar@synopsys.example.com',
    linkedin_url: 'https://www.linkedin.com/in/maheshnarbolikar6389',
    previous_company: 'Cadence Design Systems',
    previous_title: 'Staff EDA Software Engineer',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Senior EDA software architect at Synopsys. Mentorship on bipartite graph algorithms and placement scheduling engines.',
    last_contacted_at: new Date(Date.now() - 48 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 170 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 48 * 86400000).toISOString(),
  },
  {
    id: 'contact-venika-ba',
    user_id: 'user-shashank',
    full_name: 'Venika B A',
    company: 'Sabre',
    title: 'Site Reliability Engineer 1',
    email: 'venika.ba@sabre.example.com',
    linkedin_url: 'https://www.linkedin.com/in/venika-b-a-074431309',
    previous_company: 'Sabre Travel Solutions',
    previous_title: 'Cloud DevOps Intern',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'SRE at Sabre. Best practices on high-availability cloud deployments, fault-tolerant retries, and graceful degradation.',
    last_contacted_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 110 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 27 * 86400000).toISOString(),
  },
  {
    id: 'contact-koushik-senapati',
    user_id: 'user-shashank',
    full_name: 'Koushik Senapati',
    company: 'Yokogawa',
    title: 'Senior DevOps Test Engineer',
    email: 'koushik.senapati.99@gmail.com',
    linkedin_url: 'https://www.linkedin.com/in/koushik-senapati',
    previous_company: 'Wipro Technologies',
    previous_title: 'DevOps Automation Engineer',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Senior DevOps engineer at Yokogawa. CI/CD automation, GitHub Actions matrix tests, and containerized integration pipelines.',
    last_contacted_at: new Date(Date.now() - 36 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 140 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 36 * 86400000).toISOString(),
  },
  {
    id: 'contact-abhay-shinde',
    user_id: 'user-shashank',
    full_name: 'ABHAY SHINDE',
    company: 'FlyRank AI',
    title: 'Backend AI Engineer - Intern',
    email: 'abhay.shinde@flyrank.example.ai',
    linkedin_url: 'https://www.linkedin.com/in/abhay-shinde-7648a9279',
    previous_company: 'Cognitive Minds',
    previous_title: 'NLP Research Trainee',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'AI search engine backend engineer. Collaborated on RAG retrieval optimization, hybrid BM25 + dense vector embeddings.',
    last_contacted_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 85 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'contact-prakruthi-prasad',
    user_id: 'user-shashank',
    full_name: 'Prakruthi Prasad',
    company: 'TESLA SJCE',
    title: 'Web Developer',
    email: 'prakruthi.prasad@sjce.example.edu',
    linkedin_url: 'https://www.linkedin.com/in/prakruthi-prasad-065169273',
    previous_company: 'JSSSTU Technical Council',
    previous_title: 'Frontend Volunteer',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Colleague at SJCE technical clubs. Built campus event landing pages and registration dashboards for HACK-OLYMPIC 2026.',
    last_contacted_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'contact-nipun-deept',
    user_id: 'user-shashank',
    full_name: 'Nipun Deept',
    company: 'Linux Campus Club',
    title: 'Technical Team Member',
    email: 'nipun.deept@lcc.example.org',
    linkedin_url: 'https://www.linkedin.com/in/nipundeept',
    previous_company: 'LCC SJCE',
    previous_title: 'Open Source Contributor',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Linux Campus Club collaborator at SJCE. Open-source advocacy, Linux kernel workshops, and system-level C/Rust programming.',
    last_contacted_at: new Date(Date.now() - 13 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 13 * 86400000).toISOString(),
  },
  {
    id: 'contact-aritra-mondal',
    user_id: 'user-shashank',
    full_name: 'Aritra Mondal',
    company: 'CSE SJCE JSSSTU',
    title: 'Student & Core Peer',
    email: 'aritra.mondal@jssstu.example.edu',
    linkedin_url: 'https://www.linkedin.com/in/aritra-mondal-b0331b361',
    previous_company: 'JSSSTU Hackathon Cell',
    previous_title: 'Organizer',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Classmate and hackathon peer at JSS STU CSE. Worked together on HACK-OLYMPIC 2026 organizing and CampusSearch marketplace.',
    last_contacted_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'contact-avinash-reddy',
    user_id: 'user-shashank',
    full_name: 'Avinash Reddy',
    company: 'DarTechXsolutions',
    title: 'Founder & Creator',
    email: 'avinash@dartechx.example.com',
    linkedin_url: 'https://www.linkedin.com/in/avinashreddydonthiri',
    previous_company: 'DarTechX Labs',
    previous_title: 'Lead Architect',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Founder at DarTechX. Startup mentorship, venture building, and discussion on AI-powered developer tool platforms.',
    last_contacted_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 105 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'contact-dr-elena-rostova',
    user_id: 'user-shashank',
    full_name: 'Dr. Elena Rostova',
    company: 'Google DeepMind',
    title: 'Principal Research Scientist — Foundation Agents',
    email: 'elena.rostova@deepmind.example.com',
    linkedin_url: 'https://linkedin.com/in/elena-rostova-ai',
    previous_company: 'Google Brain',
    previous_title: 'Senior Staff AI Scientist',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Research advisor & collaborator. Discussed autonomous LangGraph state orchestrators, agentic consensus, and benchmark evaluations.',
    last_contacted_at: new Date(Date.now() - 41 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 41 * 86400000).toISOString(),
  },
  {
    id: 'contact-marcus-vance',
    user_id: 'user-shashank',
    full_name: 'Marcus Vance',
    company: 'Benchmark Capital',
    title: 'General Partner — Enterprise Infrastructure',
    email: 'marcus@benchmark.example.com',
    linkedin_url: 'https://linkedin.com/in/marcus-vance-vc',
    previous_company: 'Sequoia Capital',
    previous_title: 'Principal Investor',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Venture partner in enterprise infrastructure. Requested product telemetry metrics and architecture brief for offline-first sync engines.',
    last_contacted_at: new Date(Date.now() - 34 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 150 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 34 * 86400000).toISOString(),
  }
];

export const DEMO_INTERACTIONS: Interaction[] = [
  {
    id: 'demo-int-1',
    contact_id: 'contact-sandeep-guna',
    user_id: 'user-shashank',
    type: 'call',
    content: 'Deep-dive on zero-trust identity architectures and HMAC SHA-256 rotating token generation for Smart Attendance.',
    created_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
  {
    id: 'demo-int-2',
    contact_id: 'contact-pravallika-varikuti',
    user_id: 'user-shashank',
    type: 'message',
    content: 'Discussed Bosch automotive IoT telemetry benchmarks and distributed streaming queues in Node.js.',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'demo-int-3',
    contact_id: 'contact-nagesh-bhavi',
    user_id: 'user-shashank',
    type: 'note',
    content: 'Reviewing HPE hybrid cloud deployment topologies for DevFlow Pro real-time analytics.',
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
  },
  {
    id: 'demo-int-4',
    contact_id: 'contact-aritra-mondal',
    user_id: 'user-shashank',
    type: 'call',
    content: 'Finalized student registration workflows and judging criteria for HACK-OLYMPIC 2026 at JSS STU.',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  }
];
