// ═══════════════════════════════════════════════════════
// NetPlus — Judge & Recruiter Sandbox Demo Dataset
// ═══════════════════════════════════════════════════════
import { Contact, Interaction } from './types';

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'demo-1',
    user_id: 'demo-user',
    full_name: 'Dr. Elena Rostova',
    company: 'Google DeepMind',
    title: 'Principal Research Scientist — Foundation Agents',
    email: 'elena.rostova@deepmind.example.com',
    linkedin_url: 'https://linkedin.com/in/elena-rostova-ai',
    previous_company: 'Google Brain',
    previous_title: 'Senior Staff AI Scientist',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Key connection from Agentic AI Summit. Discussed autonomous LangGraph state orchestrators and benchmark evaluations.',
    last_contacted_at: new Date(Date.now() - 42 * 86400000).toISOString(), // 42 days ago
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 42 * 86400000).toISOString(),
  },
  {
    id: 'demo-2',
    user_id: 'demo-user',
    full_name: 'Marcus Vance',
    company: 'Benchmark Capital',
    title: 'General Partner — Enterprise Infrastructure',
    email: 'marcus@benchmark.example.com',
    linkedin_url: 'https://linkedin.com/in/marcus-vance-vc',
    previous_company: 'Sequoia Capital',
    previous_title: 'Principal Investor',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Requested product telemetry metrics and architecture brief for offline-first sync engines.',
    last_contacted_at: new Date(Date.now() - 35 * 86400000).toISOString(), // 35 days ago
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 150 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'demo-3',
    user_id: 'demo-user',
    full_name: 'Aria Chen',
    company: 'Stripe',
    title: 'Engineering Director — Global Payments Core',
    email: 'aria.chen@stripe.example.com',
    linkedin_url: 'https://linkedin.com/in/aria-chen-payments',
    previous_company: 'Amazon Web Services',
    previous_title: 'Senior Engineering Manager',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Ex-Amazon Principal. Mentoring on idempotent payment queue reconciliation and distributed consensus.',
    last_contacted_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'demo-4',
    user_id: 'demo-user',
    full_name: 'Rohan Mehta',
    company: 'ScaleOps Technologies',
    title: 'Co-Founder & CTO',
    email: 'rohan@scaleops.example.io',
    linkedin_url: 'https://linkedin.com/in/rohan-mehta-cto',
    previous_company: 'Flipkart',
    previous_title: 'Lead Architect',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Met at Bangalore Tech Summit. Discussing B2B CRM telemetry plugins and automated lead arbitration.',
    last_contacted_at: new Date(Date.now() - 55 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 55 * 86400000).toISOString(),
  },
  {
    id: 'demo-5',
    user_id: 'demo-user',
    full_name: 'Sarah Jenkins',
    company: 'Vercel',
    title: 'Staff Platform Architect — Edge Runtime',
    email: 'sarah.j@vercel.example.com',
    linkedin_url: 'https://linkedin.com/in/sarah-jenkins-edge',
    previous_company: 'Cloudflare',
    previous_title: 'Senior Systems Engineer',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Collaborated on Next.js edge middleware proxy architecture and SSR performance tuning.',
    last_contacted_at: new Date(Date.now() - 48 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 48 * 86400000).toISOString(),
  },
  {
    id: 'demo-6',
    user_id: 'demo-user',
    full_name: 'Kavita Nair',
    company: 'Sequoia Capital India (Peak XV)',
    title: 'Vice President — Enterprise & DeepTech',
    email: 'kavita@peakxv.example.com',
    linkedin_url: 'https://linkedin.com/in/kavita-nair-vc',
    previous_company: 'Matrix Partners',
    previous_title: 'Senior Associate',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Interested in AI-driven CRM workflow agents and Campus hardware network scalability.',
    last_contacted_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 32 * 86400000).toISOString(),
  },
  {
    id: 'demo-7',
    user_id: 'demo-user',
    full_name: "Liam O'Connor",
    company: 'Figma',
    title: 'Head of Product — Developer Ecosystem',
    email: 'liam@figma.example.com',
    linkedin_url: 'https://linkedin.com/in/liam-oconnor-design',
    previous_company: 'Atlassian',
    previous_title: 'Principal Product Manager',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Discussed interactive canvas nodes and Generative UI state synchronizers.',
    last_contacted_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 200 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'demo-8',
    user_id: 'demo-user',
    full_name: 'Devon Brooks',
    company: 'Datadog',
    title: 'VP Engineering — Observability & Telemetry',
    email: 'devon.b@datadog.example.com',
    linkedin_url: 'https://linkedin.com/in/devon-brooks-eng',
    previous_company: 'New Relic',
    previous_title: 'Director of SRE',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Gave feedback on real-time SSE metrics and simulated sensor cold-chain telemetry.',
    last_contacted_at: new Date(Date.now() - 70 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 240 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 70 * 86400000).toISOString(),
  },
  {
    id: 'demo-9',
    user_id: 'demo-user',
    full_name: 'Priya Sharma',
    company: 'Anthropic',
    title: 'Member of Technical Staff — Alignment & Reasoning',
    email: 'priya.sharma@anthropic.example.com',
    linkedin_url: 'https://linkedin.com/in/priya-sharma-ai',
    previous_company: 'Google Research',
    previous_title: 'Research Scientist',
    source: 'linkedin',
    relationship_tier: 'priority',
    notes: 'Ex-Google Brain researcher. Discussed context compression and dynamic prompt pruning.',
    last_contacted_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'demo-10',
    user_id: 'demo-user',
    full_name: 'Alexander Wright',
    company: 'Microsoft Azure',
    title: 'Principal Cloud Architect',
    email: 'alex.wright@microsoft.example.com',
    linkedin_url: 'https://linkedin.com/in/alex-wright-azure',
    previous_company: 'Oracle Cloud',
    previous_title: 'Senior Cloud Consultant',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Mentoring on multi-tenant database partitioning and zero-trust VPC peering.',
    last_contacted_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 170 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'demo-11',
    user_id: 'demo-user',
    full_name: 'Tanvi Kulkarni',
    company: 'Razorpay',
    title: 'Lead Product Manager — Banking APIs',
    email: 'tanvi.k@razorpay.example.com',
    linkedin_url: 'https://linkedin.com/in/tanvi-kulkarni-fintech',
    previous_company: 'Paytm',
    previous_title: 'Senior Product Manager',
    source: 'linkedin',
    relationship_tier: 'warm',
    notes: 'Provided architectural critique on peer-to-peer UPI dynamic string generation and settlement webhooks.',
    last_contacted_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 140 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 86400000).toISOString(),
  },
  {
    id: 'demo-12',
    user_id: 'demo-user',
    full_name: 'David Kim',
    company: 'OpenAI',
    title: 'Developer Relations Lead',
    email: 'david.kim@openai.example.com',
    linkedin_url: 'https://linkedin.com/in/david-kim-devrel',
    previous_company: 'Twilio',
    previous_title: 'Developer Evangelist',
    source: 'linkedin',
    relationship_tier: 'cold',
    notes: 'Initial contact via hackathon judging. Followed up regarding model distillation benchmarks.',
    last_contacted_at: new Date(Date.now() - 95 * 86400000).toISOString(),
    last_bulk_synced_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    last_enriched_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 220 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 95 * 86400000).toISOString(),
  }
];

export const DEMO_INTERACTIONS: Interaction[] = [
  {
    id: 'demo-int-1',
    contact_id: 'demo-1',
    user_id: 'demo-user',
    type: 'note',
    content: '1-on-1 discussion on Agentic AI Day hackathon submission. Elena shared feedback on StateGraph error boundaries.',
    created_at: new Date(Date.now() - 42 * 86400000).toISOString(),
  },
  {
    id: 'demo-int-2',
    contact_id: 'demo-2',
    user_id: 'demo-user',
    type: 'message',
    content: 'Sent executive summary deck of CampusSearch peer hardware network and offline QR attendance architecture.',
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'demo-int-3',
    contact_id: 'demo-3',
    user_id: 'demo-user',
    type: 'call',
    content: 'Discussed high-concurrency payment queues and PostgreSQL row locking strategies.',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  }
];
