'use client';

// ═══════════════════════════════════════════════════════
// Daily Digest — Home Page (Transformed UI/UX)
// High-performance dashboard with framer-motion,
// visual urgency cards, stat grid, and clean hierarchy.
// ═══════════════════════════════════════════════════════

import { useEffect, useState, useRef } from 'react';
import { format } from 'date-fns';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Zap,
  CheckCircle2,
  Clock,
  AlertTriangle,
  RotateCcw,
  Sparkles,
  FileText,
  Send,
  Trophy,
  MoreHorizontal,
  Flame,
  Star,
  Activity,
  Check,
} from 'lucide-react';
import type { UserSettings, DigestContact } from '@/lib/types';
import { DEFAULT_SETTINGS } from '@/lib/types';
import { calculatePriorityScore, getSuggestedReason, isContactOverdue } from '@/lib/scoring';
import { netPulseStore } from '@/lib/storage/db';
import { NetworkHealthCard } from '@/components/network-health-card';
import { SpeedRunModal } from '@/components/speed-run-modal';
import { PitchDeckModal } from '@/components/pitch-deck-modal';
import { ContactCard } from '@/components/contact-card';
import { soundFx } from '@/lib/sound';

export default function DigestPage() {
  const [contacts, setContacts] = useState<DigestContact[]>([]);
  const [loading, setLoading] = useState(true);
  const [contactedToday, setContactedToday] = useState<Set<string>>(new Set());
  const [snoozedIds, setSnoozedIds] = useState<Set<string>>(new Set());
  const [digestFilter, setDigestFilter] = useState<'all' | 'priority' | 'overdue'>('all');
  const [toast, setToast] = useState<string | null>(null);
  const [decayOffsetDays, setDecayOffsetDays] = useState<number>(0);
  const [speedRunOpen, setSpeedRunOpen] = useState(false);
  const [pitchDeckOpen, setPitchDeckOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const loadData = async () => {
    setLoading(true);
    const rawContacts = await netPulseStore.getContacts();
    const offset = await netPulseStore.getDecayOffsetDays();
    setDecayOffsetDays(offset);

    const userSettings = DEFAULT_SETTINGS as UserSettings;
    const simulatedNow = Date.now() + offset * 24 * 60 * 60 * 1000;

    const scored: DigestContact[] = rawContacts.map(contact => {
      const interactionCount = 1;
      const scoreData = calculatePriorityScore(contact, interactionCount, userSettings, offset);
      const overdue = isContactOverdue(contact, userSettings, offset);
      const daysSince = contact.last_contacted_at
        ? Math.floor((simulatedNow - new Date(contact.last_contacted_at).getTime()) / (1000 * 60 * 60 * 24))
        : null;

      return {
        ...contact,
        priority_score: {
          id: '',
          contact_id: contact.id,
          user_id: 'local-user',
          last_calculated_at: new Date().toISOString(),
          ...scoreData,
        },
        days_since_contact: daysSince,
        is_overdue: overdue,
        suggested_reason: getSuggestedReason(contact, scoreData.score, userSettings, offset),
      };
    });

    scored.sort((a, b) => (b.priority_score?.score || 0) - (a.priority_score?.score || 0));
    setContacts(scored);
    setLoading(false);
  };

  useEffect(() => {
    loadData();
    const handleUpdate = () => loadData();
    window.addEventListener('netpulse:state-changed', handleUpdate);
    return () => window.removeEventListener('netpulse:state-changed', handleUpdate);
  }, []);

  // Close overflow menu on click outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    };
    if (menuOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [menuOpen]);

  const markContacted = async (contactId: string) => {
    soundFx.playSuccessChime();
    await netPulseStore.markContacted(contactId);
    setContactedToday(prev => new Set([...prev, contactId]));
    showToast('Logged interaction & updated urgency clock to today!');
    await loadData();
  };

  const snoozeContact = (id: string, name: string) => {
    setSnoozedIds(prev => new Set([...prev, id]));
    showToast(`Snoozed ${name} for 7 days.`);
  };

  const handleResetDecay = async () => {
    await netPulseStore.setDecayOffsetDays(0);
    setDecayOffsetDays(0);
    window.dispatchEvent(new CustomEvent('netpulse:state-changed', { detail: { offsetDays: 0 } }));
    showToast('Reset decay simulation to baseline calendar horizon.');
  };

  const showToast = (message: string) => {
    setToast(message);
    setTimeout(() => setToast(null), 3200);
  };

  const handleExportMarkdown = () => {
    const md = [
      `# ⚡ NetPulse Daily Relationship Digest — ${format(new Date(), 'EEEE, MMMM d, yyyy')}`,
      `> Generated by NetPulse CRM Engine | ${contacts.length} Connections Requiring Attention`,
      '',
      '## 🎯 Priority Queue Today',
      ...contacts.slice(0, 15).map((c, i) =>
        `${i + 1}. **${c.full_name}** (${c.title || 'Leader'} at ${c.company || 'Enterprise'})\n   - Tier: ${c.relationship_tier.toUpperCase()} | Decay Urgency: ${c.priority_score?.score ?? 0}/100\n   - Cadence Status: ${c.suggested_reason}\n   - Suggested Action: Outreach via LinkedIn/WhatsApp or sync meeting`
      ),
      '',
      '---',
      '*Never let a good connection go cold.*'
    ].join('\n');

    navigator.clipboard.writeText(md);
    showToast('Copied formatted Markdown digest to clipboard for Notion/Slack!');
    setMenuOpen(false);
  };

  const handleSimulateCron = () => {
    showToast('⚡ Simulated 8:00 AM Cron: Dispatched morning digest notification payload!');
    setMenuOpen(false);
  };

  const today = format(new Date(), 'EEEE, MMMM d, yyyy');
  const completedCount = contactedToday.size;
  const overdueCount = contacts.filter(c => c.is_overdue).length;
  const priorityCount = contacts.filter(c => c.relationship_tier === 'priority').length;

  const visibleContacts = contacts.filter(c => {
    if (snoozedIds.has(c.id)) return false;
    if (digestFilter === 'priority') return c.relationship_tier === 'priority';
    if (digestFilter === 'overdue') return c.is_overdue;
    return true;
  });

  if (loading) {
    return (
      <div className="page-container" style={{ maxWidth: 1100 }}>
        <div className="skeleton" style={{ height: 36, width: 240, marginBottom: 8 }} />
        <div className="skeleton" style={{ height: 20, width: 160, marginBottom: 28 }} />
        <div className="stat-grid">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="skeleton" style={{ height: 110, borderRadius: 14 }} />
          ))}
        </div>
        <div className="skeleton" style={{ height: 140, borderRadius: 16, marginBottom: 24 }} />
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="skeleton" style={{ height: 74, borderRadius: 14 }} />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="page-container" style={{ maxWidth: 1100 }}>
      {/* Simulation Banner */}
      {decayOffsetDays > 0 && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '12px 18px',
            backgroundColor: 'rgba(239, 68, 68, 0.12)',
            border: '1px solid rgba(239, 68, 68, 0.35)',
            borderRadius: 12,
            marginBottom: 20,
            fontSize: '0.86rem',
            color: '#f8fafc',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <AlertTriangle size={18} color="#ef4444" />
            <span>
              <strong>Simulated Decay Active (+{decayOffsetDays} Days):</strong> Priority scores recalculated via half-life decay equations.
            </span>
          </div>
          <button
            onClick={handleResetDecay}
            style={{
              background: 'none',
              border: '1px solid rgba(239, 68, 68, 0.5)',
              color: '#ef4444',
              padding: '4px 10px',
              borderRadius: 6,
              fontSize: '0.78rem',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: 4,
            }}
          >
            <RotateCcw size={13} /> Reset Horizon
          </button>
        </motion.div>
      )}

      {/* Modern Clean Header */}
      <div
        className="page-header"
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          flexWrap: 'wrap',
          gap: 16,
          marginBottom: 28,
        }}
      >
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
            <span
              style={{
                fontSize: '0.72rem',
                fontWeight: 700,
                color: 'var(--np-accent)',
                backgroundColor: 'var(--np-accent-light)',
                padding: '2px 8px',
                borderRadius: 6,
                letterSpacing: '0.04em',
                textTransform: 'uppercase',
              }}
            >
              Executive Steward
            </span>
            <span style={{ fontSize: '0.78rem', color: 'var(--np-text-tertiary)' }}>
              Deterministic Cadence Intelligence
            </span>
          </div>
          <h1 style={{ fontSize: '1.9rem', fontWeight: 800, margin: 0, letterSpacing: '-0.02em' }}>
            Daily Digest
          </h1>
          <p style={{ margin: '4px 0 0', color: 'var(--np-text-secondary)', fontSize: '0.88rem' }}>
            {today}
          </p>
        </div>

        {/* Header Action Strip */}
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          {/* Primary High-Velocity CTA */}
          <button
            onClick={() => setSpeedRunOpen(true)}
            className="btn btn-primary"
            style={{
              padding: '10px 18px',
              fontWeight: 700,
              fontSize: '0.88rem',
              borderRadius: 10,
              boxShadow: '0 4px 16px rgba(79, 70, 229, 0.35)',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
            }}
            title="Start 60-Second Batch Outreach Power Mode"
          >
            <Zap size={16} /> 60s Speed Run
          </button>

          {/* Time-Travel Simulator Sandbox */}
          <button
            onClick={() => window.dispatchEvent(new CustomEvent('netpulse:open-simulator'))}
            className="btn btn-secondary"
            style={{
              padding: '9px 14px',
              borderColor: 'rgba(56, 189, 248, 0.4)',
              color: '#38bdf8',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              borderRadius: 10,
            }}
            title="Launch Time-Travel Decay Simulator"
          >
            <Clock size={15} /> Time-Travel
          </button>

          {/* Clean Overflow Dropdown */}
          <div className="overflow-menu" ref={menuRef}>
            <button
              onClick={() => setMenuOpen(!menuOpen)}
              className="overflow-trigger"
              title="More options"
              aria-label="More options"
            >
              <MoreHorizontal size={16} />
            </button>

            {menuOpen && (
              <div className="overflow-dropdown">
                <button
                  onClick={() => { setPitchDeckOpen(true); setMenuOpen(false); }}
                >
                  <Trophy size={14} color="#f59e0b" />
                  <span>Imagine Cup Deck</span>
                </button>
                <button onClick={handleExportMarkdown}>
                  <FileText size={14} />
                  <span>Export Markdown</span>
                </button>
                <button onClick={handleSimulateCron}>
                  <Send size={14} color="#10b981" />
                  <span>Simulate 8 AM Cron</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Dashboard Stat Grid */}
      <div className="stat-grid">
        {/* Card 1: Attention Required */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
          className="stat-card"
          style={{ '--stat-accent': 'var(--np-accent)' } as React.CSSProperties}
        >
          <div
            className="stat-icon"
            style={{ backgroundColor: 'var(--np-accent-light)', color: 'var(--np-accent)' }}
          >
            <Zap size={18} />
          </div>
          <div className="stat-value" style={{ color: 'var(--np-text-primary)' }}>
            {contacts.length - completedCount}
          </div>
          <div className="stat-label">Require Attention Today</div>
        </motion.div>

        {/* Card 2: SLA Overdue */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className={`stat-card ${overdueCount > 0 ? 'glow-red' : ''}`}
          style={{ '--stat-accent': 'var(--np-danger)' } as React.CSSProperties}
        >
          <div
            className="stat-icon"
            style={{ backgroundColor: 'rgba(239, 68, 68, 0.12)', color: '#ef4444' }}
          >
            <Flame size={18} />
          </div>
          <div className="stat-value" style={{ color: overdueCount > 0 ? '#ef4444' : 'inherit' }}>
            {overdueCount}
          </div>
          <div className="stat-label">SLA Breaches Pending</div>
        </motion.div>

        {/* Card 3: Priority Tier */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="stat-card"
          style={{ '--stat-accent': 'var(--np-warning)' } as React.CSSProperties}
        >
          <div
            className="stat-icon"
            style={{ backgroundColor: 'rgba(245, 158, 11, 0.12)', color: '#f59e0b' }}
          >
            <Star size={18} />
          </div>
          <div className="stat-value" style={{ color: 'var(--np-text-primary)' }}>
            {priorityCount}
          </div>
          <div className="stat-label">Priority Tier Leaders</div>
        </motion.div>

        {/* Card 4: Daily Actions Completed */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="stat-card"
          style={{ '--stat-accent': 'var(--np-success)' } as React.CSSProperties}
        >
          <div
            className="stat-icon"
            style={{ backgroundColor: 'rgba(16, 185, 129, 0.12)', color: '#10b981' }}
          >
            <Activity size={18} />
          </div>
          <div className="stat-value" style={{ color: '#10b981' }}>
            {completedCount}
          </div>
          <div className="stat-label">Interactions Logged Today</div>
        </motion.div>
      </div>

      {/* SLA Telemetry Bar */}
      <div style={{ marginBottom: 28 }}>
        <NetworkHealthCard />
      </div>

      {/* Filter Tabs & Section Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 16,
          flexWrap: 'wrap',
          gap: 12,
        }}
      >
        {/* Filter Pills */}
        <div className="filter-tabs">
          <button
            onClick={() => setDigestFilter('all')}
            className={`filter-tab ${digestFilter === 'all' ? 'active' : ''}`}
          >
            All Connections ({contacts.length})
          </button>
          <button
            onClick={() => setDigestFilter('priority')}
            className={`filter-tab ${digestFilter === 'priority' ? 'active' : ''}`}
          >
            Priority Tier ({priorityCount})
          </button>
          <button
            onClick={() => setDigestFilter('overdue')}
            className={`filter-tab ${digestFilter === 'overdue' ? 'active' : ''}`}
          >
            SLA Overdue ({overdueCount})
          </button>
        </div>

        {/* Snooze Clear Button */}
        {snoozedIds.size > 0 && (
          <button
            onClick={() => { setSnoozedIds(new Set()); showToast('Restored all snoozed contacts to digest.'); }}
            className="btn btn-ghost btn-sm"
            style={{ fontSize: '0.74rem', color: 'var(--np-text-tertiary)' }}
          >
            Clear {snoozedIds.size} Snoozed
          </button>
        )}
      </div>

      {/* Contact Cards List with Framer Motion Layout Transitions */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        <AnimatePresence mode="popLayout">
          {visibleContacts.length === 0 ? (
            <motion.div
              key="empty"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="card"
              style={{ padding: 48, textAlign: 'center', borderRadius: 16 }}
            >
              <CheckCircle2 size={40} style={{ margin: '0 auto 12px auto', color: '#10b981' }} />
              <h3 style={{ fontSize: '1.25rem', fontWeight: 800, margin: '0 0 6px 0' }}>
                You&apos;re completely on top of relationships!
              </h3>
              <p style={{ color: 'var(--np-text-secondary)', fontSize: '0.88rem', margin: 0 }}>
                Zero connections in this view require immediate outreach.
              </p>
            </motion.div>
          ) : (
            visibleContacts.map((contact, index) => (
              <ContactCard
                key={contact.id}
                contact={contact}
                isCompleted={contactedToday.has(contact.id)}
                onMarkContacted={markContacted}
                onSnooze={snoozeContact}
                index={index}
              />
            ))
          )}
        </AnimatePresence>
      </div>

      {/* Morning Speed Run Batch Outreach Modal */}
      <SpeedRunModal
        isOpen={speedRunOpen}
        onClose={() => setSpeedRunOpen(false)}
        contacts={contacts}
        onCompletedAll={() => {
          soundFx.playCelebrationFanfare();
          loadData();
          showToast('🎉 Power hour completed! Cleared daily relationship SLAs.');
        }}
      />

      {/* Imagine Cup Presentation Deck Modal */}
      <PitchDeckModal
        isOpen={pitchDeckOpen}
        onClose={() => setPitchDeckOpen(false)}
      />

      {/* Floating Toast Notification */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.9 }}
            className="toast"
            style={{ display: 'flex', alignItems: 'center', gap: 10, zIndex: 6000 }}
          >
            <CheckCircle2 size={16} style={{ color: 'var(--np-success)' }} />
            <span>{toast}</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
